# Generated by Django 5.1.1 on 2024-09-06 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('author', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=100)),
                ('publish_year', models.IntegerField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book_images')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='book_pdfs')),
                ('summary', models.TextField(max_length=500)),
                ('donated_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('donar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
